### ISSUE TITLE
Client::get_posts silently loses posts when called with many IDs

### ISSUE THREAD

**Issue by castanearie** [nasso/rs621#3]
It seems that the API is silently limiting the number of posts you can search for by ID to 75, while the Client tries to process 100 at a time.

https://github.com/nasso/rs621/blob/2e99f56dcce19bd2bf48167f49b26c5b6ffbab63/src/post.rs#L449

**Comment by castanearie** [comment]
This is very old now and I don't want it bothering you

**Comment by nasso** [comment]
i haven't had a chance to look into it but it's not bothering me don't worry!! thank you for the concern.
